# Discord Webhook Configuration

# 테스트 알람
discord.webhook.test=https://discordapp.com/api/webhooks/1503266799016480789/hKfFW_aT2i4GGAIEgP22X7Qpy4pJcZ8OFFTZT1ILp9ek8UpQpNvcraq4nUuAm-5TAM2b

# 오류 알람
discord.webhook.error=https://discordapp.com/api/webhooks/1503266821191503972/HNz6z1zAmuCRmFWX__Lnx7o5DD2rCF_OpVLj4r6DUmRRXoERug9lgl013LuBysYsm9QD

# 일일보고
discord.webhook.report=https://discordapp.com/api/webhooks/1503267022350586009/qOAtlnGtm956CCz3iknbGC8Snem2cMVBlwuFawkP6MQFl0q8TJi9sW5C6Gwx-XA81Uj2

# 상담 신청 알림
discord.webhook.consultation=https://discordapp.com/api/webhooks/1503268975755137074/9jYRYGgNGJYdnQRuUpPK6-alzZlx3E9f2jIh1eVlARO4mefQb_EX0TSvOGsnkWWOFzax

# 시스템 알림 (오류 채널 사용)
discord.webhook.system=https://discordapp.com/api/webhooks/1503266821191503972/HNz6z1zAmuCRmFWX__Lnx7o5DD2rCF_OpVLj4r6DUmRRXoERug9lgl013LuBysYsm9QD

# 알림 활성화 여부
discord.enabled=true
