# Gmail SMTP Configuration
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.protocols=TLSv1.2

# Sender Account
mail.sender.email=acelaw.admin@gmail.com
mail.sender.password=mejlrkgdqrperqhj
mail.sender.name=에이스 법률사무소

# Recipients (각각 개별 발송)
mail.recipients=ace-78@naver.com,acelaw.admin@gmail.com
